### PR TITLE
Dx910 sw 99002 r9p0 01rel0 multiplatform

### PR DESCRIPTION
**Pull request by useful64**

### CODE REVIEW

**Comment by useful64** [comment]
Point out that the change on file "driver/src/devicedrv/mali/linux/mali_memory_cow.c " is 
remove carriage return "sed -i 's/\r$//g' mali_memory_cow.c" and this patch:
```

--- mali_memory_cow.c.old	2020-04-22 00:25:59.746799360 +0200
+++ mali_memory_cow.c	2020-04-22 00:26:39.461061243 +0200
@@ -529,13 +529,13 @@
 
 	list_for_each_entry(m_page, &cow->pages, list) {
 		/* We should use vm_insert_page, but it does a dcache
-		 * flush which makes it way slower than remap_pfn_range or vm_insert_pfn.
-		ret = vm_insert_page(vma, addr, page);
+		 * flush which makes it way slower than remap_pfn_range or vmf_insert_pfn.
+		ret = vmf_insert_page(vma, addr, page);
 		*/
 		ret = vmf_insert_pfn(vma, addr, _mali_page_node_get_pfn(m_page));
 
 		if (unlikely(ret & VM_FAULT_ERROR)) {
-			return -EFAULT;
+			return ret;
 		}
 		addr += _MALI_OSK_MALI_PAGE_SIZE;
 	}
```

**Comment by chewitt** [comment]
Can I ask what the target hardware and use-case is for this change? .. because LE master branch has moved to the in-kernel lima/panfrost drivers on all hardware we support. There's no major objection to keeping the sources usable for other uses, but as nothing we're running uses it now, test and merge might take a while. It would help to see some kernel and Kodi logs to prove the patch works instead of submitting it blind. Thanks.

**Comment by useful64** [comment]
Oh, I didn't know this project had been discontinued.

I was testing Armbian, in Armbian the lima driver does not work for me:
`kernel: lima ff300000.gpu: ignoring dependency for device, assuming no driver`

I know the mali driver worked for me in LE, I was going to use that one.

Compiling this driver for rock64 (mali-450) with kernel version 5.7-rc0 fails. The patch that is really necessary for the compilation is:
`driver/src/devicedrv/mali/linux/mali_memory_dma_buf.c` 

But, I will try to using the lima driver. Regards.

**Comment by useful64** [comment]
Oh, I didn't know this project had been discontinued.

I was testing Armbian, in Armbian the lima driver does not work for me. I know the mali driver worked for me in LE, I was going to use that one.

Compiling this driver for rock64 (mali-450) with kernel version 5.7-rc0 fails. The patch that is really necessary for the compilation is:
`driver/src/devicedrv/mali/linux/mali_memory_dma_buf.c`

But, I will try to using the lima driver. Regards.

**Comment by useful64** [comment]
I can confirm that "lima" driver works fine.

**Comment by chewitt** [comment]
Closing as not tested by staff and user is now blob free :)

**Pull request closed without merging**
